### ISSUE TITLE
ConvertFrom-Json in PS 5.1 does not support -Depth

### ISSUE THREAD

**Issue by potatoqualitee** [mkht/PSOpenAI#30]
Was trying out the new features 🥳  and ran into this issue

```powershell
$result = Request-ChatCompletion @params
ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\PSOpenAI\4.1.0\Public\Request-ChatCompletion.ps1:308 char:94
+ ... onse_format.json_schema = ConvertFrom-Json $JsonSchema -Depth 64 -NoE ...
+                                                            ~~~~~~
```

**Comment by mkht** [comment]
I had intended to have noticed and fixed this issue just prior to release, but the fix and testing was insufficient.

To be honest, Windows PowerShell 5.1 is becoming legacy and its support is becoming difficult. However, as long as the default version of Windows is 5.1 and MS supports it, I will not stop supporting it.

**Comment by mkht** [comment]
This issue was fixed in v4.1.1
https://github.com/mkht/PSOpenAI/releases/tag/v4.1.1

**Comment by potatoqualitee** [comment]
> However, as long as the default version of Windows is 5.1 and MS supports it, I will not stop supporting it.

Same, most of my modules will support 5.1 if it's not too hard, since that's what most corps are running.  Though it always feels nice to develop solely for 7x.

Thanks for the fix!

**Comment by potatoqualitee** [comment]
btw, you can still have this in 7.x with good ol' PSDefaultParameterValues at the top of the command. the values are only used if the parameter exists so this will work on ps 5.1 and 7.x

```powershell
$PSDefaultParameterValues["ConvertFrom-Json:Depth"] = 64
$PSDefaultParameterValues["ConvertFrom-Json:NoEnumerate"] = $true
```
